version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - src/.env
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - backend

networks:
  backend:
